spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/george-git82/configrepo
          clone-on-start: true

server:
  port: 9002
  # no trace in rest error response
  error:
    include-stacktrace: never

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
