spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761
  # no trace in rest error response
  error:
    include-stacktrace: never

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
