spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCTS-LIST
          uri: lb://PRODUCTS-LIST
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCTS-LIST
                fallbackuri: forward:/productListServiceFallback
        - id: PRODUCTS-INVENTORY
          uri: lb://PRODUCTS-INVENTORY
          predicates:
            - Path=/api/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCTS-INVENTORY
                fallbackuri: forward:/productInventoryServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

server:
  port: 9000
  # no trace in rest error response
  error:
    include-stacktrace: never

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
