spring:
  application:
    name: PRODUCTS-INVENTORY
  # JPA configs
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
  # no trace in rest error response
  error:
    include-stacktrace: never

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
